// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_GVvV9VExidN3pPjCkditl_o_O2tJtk0',
    appId: '1:301508768068:web:84a290ef243c0fb96f6711',
    messagingSenderId: '301508768068',
    projectId: 'notepad-app-miguel',
    authDomain: 'notepad-app-miguel.firebaseapp.com',
    storageBucket: 'notepad-app-miguel.appspot.com',
    measurementId: 'G-B2SX3T12WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYCkMuazKzX_Ge9onaJsD5eYzhsjn8PhI',
    appId: '1:301508768068:android:47ee41807599350a6f6711',
    messagingSenderId: '301508768068',
    projectId: 'notepad-app-miguel',
    storageBucket: 'notepad-app-miguel.appspot.com',
  );
}
